### PR TITLE
add configuration to NetCDFDataset #116

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

add configuration to the NetCDFDataset

Fixes issue #116 

## How Has This Been Tested?

1. Adjusted unittest accordingly
2. ran skipped tests too

- [ ] No
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by jacobbieker — APPROVED** [review]
LGTM! Maybe we can change the subsetting code at some point to use `t0_dt` to get the current timestep, but looks good!

**Comment by peterdudfield** [comment]
> LGTM! Maybe we can change the subsetting code at some point to use `t0_dt` to get the current timestep, but looks good!

Yea- maybe is worth me doing it now. Do you have a script to make to 0.nc test data?

**Comment by jacobbieker** [comment]
> > LGTM! Maybe we can change the subsetting code at some point to use `t0_dt` to get the current timestep, but looks good!
> 
> Yea- maybe is worth me doing it now. Do you have a script to make to 0.nc test data?

No, the structure was taken from a real example, and then just had the data part replaced with random data and then saved. I'm not the best with xarray still, so it seemed the easiest way to do it

**Comment by peterdudfield** [comment]
> > > LGTM! Maybe we can change the subsetting code at some point to use `t0_dt` to get the current timestep, but looks good!
> > 
> > 
> > Yea- maybe is worth me doing it now. Do you have a script to make to 0.nc test data?
> 
> No, the structure was taken from a real example, and then just had the data part replaced with random data and then saved. I'm not the best with xarray still, so it seemed the easiest way to do it

That's a good way to do it. I've added this issue, as a way to create it. https://github.com/openclimatefix/nowcasting_dataset/issues/161

**Review by JackKelly — COMMENTED** [review]
LGTM! (sorry for the very late review!)

**Pull request merged**
