### PR TITLE
adding an image of uk_pv locations

### PR DESCRIPTION
**Pull request by bndxn**

### CODE REVIEW

**Comment by bndxn** [comment]
Hey FYI @jacobbieker, I hope I've done the right thing - I added an image of the locations from the uk_pv dataset in case anyone finds that helpful.

**Comment by peterdudfield** [comment]
You couldnt add the script that makes that image too could you? Just incase anyone wants to tweak it a bit?

**Comment by peterdudfield** [comment]
Sorry I should have said this first, thanks @bndxn for adding this

**Comment by jacobbieker** [comment]
Yeah, thanks for adding it @bndxn! I'd also suggest adding the script to scripts/ so its easy to update if we get and release more data.

**Comment by bndxn** [comment]
No worries at all! Yeah, will do now. I can't seem to commit to this PR so I'll open a new one.

**Pull request closed without merging**
